name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]
env:
  GCP_SA_EMAIL: ${{secrets.GCP_SA_EMAIL}}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  APP_RUN_REGION: 'europe-west1'
  APP_RUN_PROJECT_ID: ${{secrets.GCP_PROJECT_ID_DEV}}
  APP_RUN_NAME: 'datawarehouse'

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    environment:
      name: dev

    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/${{env.APP_RUN_NAME}}:latest .

      - name: Push
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/${{env.APP_RUN_NAME}}:latest

      - name: Deploy
        run: |
          gcloud run deploy ${{env.APP_RUN_NAME}} \
          --region ${{env.APP_RUN_REGION}} \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/${{env.APP_RUN_NAME}} \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID_DEV }}