name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]
env:
  GCP_SA_EMAIL: ${{secrets.GCP_SA_EMAIL}}
  GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
  APP_RUN_REGION: 'europe-west1'
  APP_RUN_PROJECT_ID: ${{secrets.GCP_PROJECT_ID_DEV}}
  APP_RUN_NAME: 'datawarehouse'

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11.0.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
            # Setup gcloud CLI
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.3.0

      - uses: actions/checkout@master

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID_DEV }}/${{ env.APP_RUN_NAME }}:latest .